version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-image-gateway
    ports:
      - "8080:80"  # Truy cập qua http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - minio-net

networks:
  minio-net:
    external: true  # Nối với mạng docker đã chạy MinIO
