thoang@thoang:~/python_app/Fastapi_AI/nginx_minio$ cat docker-compose.yml
services:
  nginx:
    image: nginx:latest
    container_name: nginx-image-gateway
    ports:
      - "8080:443"  # Truy cập qua http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
thoang@thoang:~/python_app/Fastapi_AI/nginx_minio$ cat nginx.conf
events {}

http {
    upstream minio {
        server 192.168.5.11:9000;  # Tên service hoặc container của MinIO trong cùng network
    }

    server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/registry.crt;
        ssl_certificate_key /etc/nginx/certs/registry.key;

        # Public ảnh qua /images/*
        location /images/ {
            proxy_pass http://minio/product-images/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Optional caching headers
            add_header Cache-Control "public, max-age=3600";
        }
    }
}