version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: docker-registry-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
